on: [push]
name: Sonar Workflow
jobs:
  sonarTriger:
    name: Sonar Triger
    runs-on: ubuntu-latest
    steps:
    - uses: warchant/setup-sonar-scanner@v1
    - uses: actions/checkout@master
    - name: Setup sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner 
            -Dsonar.projectKey=reuse -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST }}
          




